'use client';
import Head from 'next/head';
import Image from 'next/image';
import Signin from '@/components/Signin';
import groupPic from '../public/images/group-pic.png';
import Section1 from '@/components/Section1';
import Testimonials from '@/components/Testimonials';

//import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hobby cue</title>
        <meta name="description" content="Generated by hobbycue app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="border bg-light">
        <div className="container-fluid bg-light">
          <div className="row mt-5 pt-4 ">
            <div className="col-12 col-lg-8">
              <h2>
                <span className="fw-bolder fst-italic fs-2">
                  Explore your <span style={{ color: '#0096C8' }}> hobby </span>
                  <span> or </span>
                  <span style={{ color: '#8064A2' }}> passion </span>
                </span>
              </h2>
              <p className="lh-lg">
                Sign-in to interact with a community of fellow hobbyists and an
                eco-system of experts, teachers, suppliers, classes, workshops,
                and places to practice, participate or perform. Your hobby may
                be about visual or performing arts, sports, games, gardening,
                model making, cooking, indoor or outdoor activities…
              </p>
              <p className="lh-lg">
                If you are an expert or a seller, you can Add your Listing and
                promote yourself, your students, products, services or events.
                Hop on your hobbyhorse and enjoy the ride.
              </p>
              <p>
                <Image
                  src={groupPic}
                  alt="lockIcon"
                  className="img-fluid"
                  priority
                />
              </p>
            </div>
            <div className="col-12 col-lg-4">
              <div className="d-flex justify-content-start gap-4">
                <p
                  className="fw-bold fs-4 text-decoration-underline"
                  style={{ color: '#0096C8' }}
                >
                  Sign In
                </p>
                <p className="text-muted fw-bold fs-4">Join In</p>
              </div>
              <div className="d-flex flex-column justify-content-center gap-2">
                <Signin />
              </div>
            </div>
          </div>
        </div>

        <Section1 />
        <Testimonials />
      </main>
    </>
  );
}
